"use client";
import { useEffect, useMemo, useState } from "react";

type Asset={id:string;title:string;fileName:string;originalFileName:string;kind:"image"|"document"|"audio"|"video"|"other";source:"upload"|"generated";mimeType:string;sizeBytes:number;publicUrl:string;relativePath:string;prompt?:string|null;createdAt:string;status?:"active"|"trash"};
type Tab="all"|"uploaded"|"generated"|"trash";

export default function RoyalOSAssetGallery({refreshKey=0}:{refreshKey?:number}){
 const [assets,setAssets]=useState<Asset[]>([]); const [tab,setTab]=useState<Tab>("all"); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [title,setTitle]=useState(""); const [file,setFile]=useState<File|null>(null); const [uploading,setUploading]=useState(false); const [limit,setLimit]=useState(12);
 async function load(){setLoading(true);setError("");try{const p=new URLSearchParams();if(search.trim())p.set("q",search.trim());if(tab==="uploaded")p.set("source","upload");if(tab==="generated")p.set("source","generated");p.set("status",tab==="trash"?"trash":"active");const r=await fetch(`/api/tools/assets?${p}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setAssets(d.assets||[])}catch(e){setError(e instanceof Error?e.message:"Could not load assets") }finally{setLoading(false)}}
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[refreshKey,tab]);
 const visible=useMemo(()=>assets.slice(0,limit),[assets,limit]);
 async function upload(){if(!file){setError("Choose a file first.");return}setUploading(true);const f=new FormData();f.set("file",file);if(title.trim())f.set("title",title.trim());try{const r=await fetch("/api/tools/assets/upload",{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);setFile(null);setTitle("");setTab("uploaded");await load()}catch(e){setError(e instanceof Error?e.message:"Upload failed") }finally{setUploading(false)}}
 async function action(id:string,kind:"trash"|"restore"|"delete"){if(kind==="delete"&&!window.confirm("Delete this asset permanently? This cannot be undone."))return;const r=await fetch(kind==="delete"?`/api/tools/assets?id=${encodeURIComponent(id)}`:"/api/tools/assets",{method:kind==="delete"?"DELETE":"PATCH",headers:kind==="delete"?undefined:{"Content-Type":"application/json"},body:kind==="delete"?undefined:JSON.stringify({id,action:kind})});if(!r.ok){const d=await r.json();setError(d.error||"Action failed");return}await load()}
 return <div style={{display:"grid",gap:18}}>
  <section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><h2 style={{margin:0,color:"#f6ce69"}}>RoyalOS Asset Gallery</h2><p style={{color:"#9da9ba"}}>Uploaded and AI-generated assets stay separate, searchable, recoverable, and reusable.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{(["all","uploaded","generated","trash"] as Tab[]).map(t=><button key={t} onClick={()=>{setTab(t);setLimit(12)}} style={tab===t?activeTab:tabButton}>{t==="all"?"All Assets":t==="uploaded"?"Uploaded Assets":t==="generated"?"Generated Assets":"Trash"}</button>)}</div></div>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:10}}><input style={input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Optional asset title"/><input style={input} type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button style={primary} onClick={upload} disabled={uploading}>{uploading?"Uploading…":"Upload asset"}</button></div>
   <div style={{display:"flex",gap:10}}><input style={{...input,flex:1}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search assets…"/><button style={tabButton} onClick={load}>Search</button></div>{error&&<div style={{color:"#ffb2ad"}}>{error}</div>}
  </section>
  <section style={card}><div style={{display:"flex",justifyContent:"space-between"}}><h3 style={{marginTop:0,color:"white"}}>{tab==="trash"?"Recycle Bin":tab==="generated"?"Generated Assets":tab==="uploaded"?"Uploaded Assets":"Asset Library"}</h3><span style={{color:"#8996a8"}}>{assets.length} items</span></div>{loading?<p>Loading…</p>:visible.length===0?<p style={{color:"#8f9bad"}}>No assets in this view.</p>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(210px,1fr))",gap:14}}>{visible.map(a=><article key={a.id} style={assetCard}>{a.kind==="image"?<img src={a.publicUrl} alt={a.title} style={{width:"100%",aspectRatio:"1",objectFit:"cover",borderRadius:12}}/>:<div style={{display:"grid",placeItems:"center",aspectRatio:"1",borderRadius:12,background:"#111926",fontSize:42}}>◫</div>}<strong style={{color:"white"}}>{a.title}</strong><small style={{color:"#8f9bad"}}>{a.source} • {a.kind}</small><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><a href={a.publicUrl} target="_blank" style={smallButton}>Open</a>{tab==="trash"?<><button style={smallButton} onClick={()=>action(a.id,"restore")}>Restore</button><button style={danger} onClick={()=>action(a.id,"delete")}>Delete forever</button></>:<button style={danger} onClick={()=>action(a.id,"trash")}>Move to Trash</button>}</div></article>)}</div>}{assets.length>visible.length&&<button style={{...tabButton,marginTop:16}} onClick={()=>setLimit(v=>v+12)}>See more assets</button>}</section>
 </div>
}
const card:React.CSSProperties={background:"rgba(21,27,39,.94)",border:"1px solid rgba(255,255,255,.08)",borderRadius:20,padding:22,display:"grid",gap:14};const input:React.CSSProperties={padding:"12px 14px",borderRadius:11,border:"1px solid rgba(255,255,255,.12)",background:"#101722",color:"white"};const tabButton:React.CSSProperties={padding:"10px 13px",borderRadius:10,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.04)",color:"#d9e0ea",cursor:"pointer"};const activeTab:React.CSSProperties={...tabButton,color:"#17120a",background:"#f3c557",fontWeight:900};const primary:React.CSSProperties={...activeTab,border:0};const assetCard:React.CSSProperties={display:"grid",gap:9,padding:12,borderRadius:16,border:"1px solid rgba(255,255,255,.08)",background:"rgba(255,255,255,.025)"};const smallButton:React.CSSProperties={...tabButton,padding:"7px 9px",fontSize:12,textDecoration:"none"};const danger:React.CSSProperties={...smallButton,color:"#ffb4af",borderColor:"rgba(255,100,100,.25)"};
