import type {
  BrandEmployeeAssignment,
  BrandProfile,
  BrandWebsite,
} from "@/lib/brands/types";

export const ROYALOS_BRANDS: readonly BrandProfile[] = [
  {
    id: "brand-choiceroyals",
    name: "ChoiceRoyals",
    legalName: "Triple-Hay Concept LLC",
    slug: "choiceroyals",
    description:
      "Premium education, business growth, publishing, digital products, and AI-powered company systems.",
    logoUrl: "/brands/choiceroyals/logo.png",
    primaryDomain: "https://choiceroyals.com",
    accentColor: "#e7b84f",
    accentSoft: "rgba(231, 184, 79, 0.16)",
    workspaceId: "workspace-choice-royals",
    status: "active",
    category: "Education & Business Platform",
    missionStatement: "Learn. Grow. Build.",
  },
  {
    id: "brand-xena-grace",
    name: "Xena Grace",
    slug: "xena-grace",
    description:
      "A cinematic music and storytelling brand focused on motivation, healing, emotional strength, faith, and uplifting community.",
    logoUrl: "/brands/xena-grace/logo.png",
    primaryDomain: "https://xgrace.net",
    accentColor: "#d89af5",
    accentSoft: "rgba(216, 154, 245, 0.16)",
    workspaceId: "workspace-xena-grace",
    status: "active",
    category: "Music, Storytelling & Community",
    missionStatement: "Music, healing, hope, and human connection.",
  },
  {
    id: "brand-td-talk",
    name: "TD Talk",
    slug: "td-talk",
    description:
      "A conversation and media brand for deep discussions, interviews, testimony, learning, and community.",
    logoUrl: "/brands/td-talk/logo.png",
    primaryDomain: "",
    accentColor: "#74dfb6",
    accentSoft: "rgba(116, 223, 182, 0.15)",
    workspaceId: "workspace-td-talk",
    status: "setup",
    category: "Media & Conversation",
    missionStatement: "Meaningful conversations that help people grow.",
  },
  {
    id: "brand-triple-hay",
    name: "Triple-Hay Concept LLC",
    legalName: "Triple-Hay Concept LLC",
    slug: "triple-hay",
    description:
      "The parent company responsible for governance, shared operations, strategy, finance, security, and the RoyalOS platform.",
    logoUrl: "/brands/triple-hay/logo.png",
    primaryDomain: "",
    accentColor: "#7aaeff",
    accentSoft: "rgba(122, 174, 255, 0.15)",
    workspaceId: "workspace-triple-hay",
    status: "active",
    category: "Parent Company",
    missionStatement: "Build durable brands, systems, and opportunities.",
  },
] as const;

export const BRAND_WEBSITES_SEED: readonly BrandWebsite[] = [
  {
    id: "site-choiceroyals-main",
    brandId: "brand-choiceroyals",
    label: "Main Website",
    url: "https://choiceroyals.com",
    kind: "main",
    provider: "WordPress",
    health: "not_checked",
    sslStatus: "not_checked",
    assignedEmployees: ["Orion", "Sentinel", "Emmy"],
  },
  {
    id: "site-xena-main",
    brandId: "brand-xena-grace",
    label: "Xena Grace Gateway",
    url: "https://xgrace.net",
    kind: "main",
    provider: "WordPress",
    health: "not_checked",
    sslStatus: "not_checked",
    assignedEmployees: ["Orion", "Sentinel", "Emmy", "Janet"],
  },
  {
    id: "site-xena-community",
    brandId: "brand-xena-grace",
    label: "Live Feed Community",
    url: "https://xgrace.net",
    kind: "community",
    provider: "WordPress",
    health: "not_checked",
    sslStatus: "not_checked",
    assignedEmployees: ["Janet", "Emmy", "Sentinel"],
  },
] as const;

export const BRAND_ASSIGNMENTS_SEED: readonly BrandEmployeeAssignment[] = [
  {
    id: "assignment-choice-emmy",
    brandId: "brand-choiceroyals",
    employee: "Emmy",
    responsibility: "Marketing strategy, content calendar, social publishing, and engagement reporting.",
    platformIds: ["facebook", "instagram", "linkedin", "x", "tiktok", "wordpress", "metricool"],
    canDraft: true,
    canSchedule: true,
    canPublish: false,
    publishRequiresApproval: true,
    canReadAnalytics: true,
  },
  {
    id: "assignment-choice-orion",
    brandId: "brand-choiceroyals",
    employee: "Orion",
    responsibility: "Website, API, integration, architecture, deployment, and technical reliability.",
    platformIds: ["wordpress", "github", "supabase"],
    canDraft: true,
    canSchedule: false,
    canPublish: false,
    publishRequiresApproval: true,
    canReadAnalytics: true,
  },
  {
    id: "assignment-choice-sentinel",
    brandId: "brand-choiceroyals",
    employee: "Sentinel",
    responsibility: "Security monitoring, platform audit, incidents, access reviews, and recommendations.",
    platformIds: ["facebook", "instagram", "linkedin", "x", "tiktok", "youtube", "wordpress", "metricool", "github", "supabase", "stripe"],
    canDraft: false,
    canSchedule: false,
    canPublish: false,
    publishRequiresApproval: true,
    canReadAnalytics: true,
  },
  {
    id: "assignment-xena-emmy",
    brandId: "brand-xena-grace",
    employee: "Emmy",
    responsibility: "Release campaigns, community growth, captions, social publishing, and audience development.",
    platformIds: ["facebook", "instagram", "x", "tiktok", "youtube", "wordpress", "metricool"],
    canDraft: true,
    canSchedule: true,
    canPublish: false,
    publishRequiresApproval: true,
    canReadAnalytics: true,
  },
  {
    id: "assignment-xena-cine",
    brandId: "brand-xena-grace",
    employee: "Cine",
    responsibility: "AI music visuals, short-form video, lyric videos, trailers, thumbnails, and media handoff.",
    platformIds: ["instagram", "tiktok", "youtube", "metricool"],
    canDraft: true,
    canSchedule: false,
    canPublish: false,
    publishRequiresApproval: true,
    canReadAnalytics: false,
  },
  {
    id: "assignment-xena-jack",
    brandId: "brand-xena-grace",
    employee: "Jack",
    responsibility: "Media strategy, production quality, final review, and YouTube publishing preparation.",
    platformIds: ["youtube", "instagram", "tiktok"],
    canDraft: true,
    canSchedule: true,
    canPublish: false,
    publishRequiresApproval: true,
    canReadAnalytics: true,
  },
  {
    id: "assignment-xena-sentinel",
    brandId: "brand-xena-grace",
    employee: "Sentinel",
    responsibility: "Website, community, account, and platform security monitoring and audit reporting.",
    platformIds: ["facebook", "instagram", "x", "tiktok", "youtube", "wordpress", "metricool", "supabase"],
    canDraft: false,
    canSchedule: false,
    canPublish: false,
    publishRequiresApproval: true,
    canReadAnalytics: true,
  },
];

export function getBrandById(id: string): BrandProfile | undefined {
  return ROYALOS_BRANDS.find((brand) => brand.id === id);
}

export function getBrandBySlug(slug: string): BrandProfile | undefined {
  return ROYALOS_BRANDS.find((brand) => brand.slug === slug);
}
