import type { CoreOperationsState } from "./types";

const now = new Date().toISOString();

export const CORE_OPERATIONS_SEED: CoreOperationsState = {
  version: 1,
  updatedAt: now,
  workspaces: [
    {
      id: "workspace-triple-hay",
      name: "Triple-Hay Concept LLC",
      type: "Parent Company",
      description: "Executive oversight, company strategy, shared operations, and governance.",
      status: "Active",
      accent: "#f4b942",
      memberCount: 11,
      missionCount: 2,
      documentCount: 18,
      createdAt: now,
    },
    {
      id: "workspace-choice-royals",
      name: "ChoiceRoyals",
      type: "Education & Business Platform",
      description: "Courses, books, business tools, customer growth, and RoyalOS development.",
      status: "Active",
      accent: "#7cc7ff",
      memberCount: 8,
      missionCount: 3,
      documentCount: 42,
      createdAt: now,
    },
    {
      id: "workspace-xena-grace",
      name: "Xena Grace",
      type: "Music & Media Brand",
      description: "Song catalog, releases, visuals, audience growth, and media production.",
      status: "Active",
      accent: "#e99bff",
      memberCount: 6,
      missionCount: 2,
      documentCount: 31,
      createdAt: now,
    },
    {
      id: "workspace-td-talk",
      name: "TD Talk",
      type: "Media & Conversation Brand",
      description: "Deep conversations, interviews, podcasts, and community content.",
      status: "Active",
      accent: "#7de2b8",
      memberCount: 5,
      missionCount: 1,
      documentCount: 12,
      createdAt: now,
    },
  ],
  missions: [
    {
      id: "mission-cybersecurity-webinar",
      title: "Cybersecurity Webinar Launch",
      workspaceId: "workspace-choice-royals",
      description: "Prepare curriculum, landing page, promotional content, and launch sequence.",
      leadEmployee: "Adedeji",
      supportingEmployees: ["Emmy", "Nova", "Atlas", "Titan"],
      priority: "High",
      status: "In Progress",
      progress: 65,
      dueDate: "2026-08-15",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "mission-business-growth",
      title: "Q3 Business Growth Strategy",
      workspaceId: "workspace-triple-hay",
      description: "Create a focused growth plan across ChoiceRoyals, Xena Grace, and RoyalOS.",
      leadEmployee: "Atlas",
      supportingEmployees: ["Adedeji", "Tyson", "Titan"],
      priority: "High",
      status: "In Progress",
      progress: 40,
      dueDate: "2026-09-01",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "mission-ai-course",
      title: "AI Course Production Pipeline",
      workspaceId: "workspace-choice-royals",
      description: "Organize course lessons, graphics, videos, publishing, and student onboarding.",
      leadEmployee: "Titan",
      supportingEmployees: ["Emmy", "Nova", "Cine", "Jack"],
      priority: "Normal",
      status: "Planning",
      progress: 25,
      dueDate: "2026-10-10",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "mission-xena-marketing",
      title: "Xena Grace Music Marketing Plan",
      workspaceId: "workspace-xena-grace",
      description: "Coordinate visual assets, short-form video, social calendar, and release promotion.",
      leadEmployee: "Emmy",
      supportingEmployees: ["Cine", "Nova", "Jack", "Atlas"],
      priority: "Critical",
      status: "In Progress",
      progress: 70,
      dueDate: "2026-08-01",
      createdAt: now,
      updatedAt: now,
    },
  ],
  approvals: [
    {
      id: "approval-xena-reel",
      title: "Approve Xena Grace release Reel",
      kind: "Social post",
      workspaceId: "workspace-xena-grace",
      requestedBy: "Emmy",
      summary: "Vertical launch Reel with Cine video, caption, hashtags, and release link.",
      status: "Pending",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "approval-course-cover",
      title: "Approve cybersecurity course cover",
      kind: "Creative asset",
      workspaceId: "workspace-choice-royals",
      requestedBy: "Nova",
      summary: "Final 16:9 course cover and square social-media version.",
      status: "Pending",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "approval-bookkeeping-category",
      title: "Review uncategorized software expense",
      kind: "Accounting review",
      workspaceId: "workspace-triple-hay",
      requestedBy: "Michael P",
      summary: "Confirm whether the transaction belongs under software, media production, or education.",
      status: "Pending",
      createdAt: now,
      updatedAt: now,
    },
  ],
  knowledge: [
    {
      id: "knowledge-company-roadmap",
      title: "RoyalOS Product Roadmap",
      workspaceId: "workspace-triple-hay",
      category: "Strategy",
      source: "ROYALOS_PRODUCT_ROADMAP.md",
      status: "Indexed",
      access: ["Adedeji", "Orion", "Titan", "Atlas"],
      notes: "Official multi-phase roadmap for RoyalOS development and commercialization.",
      updatedAt: now,
    },
    {
      id: "knowledge-xena-catalog",
      title: "Xena Grace Song Catalog",
      workspaceId: "workspace-xena-grace",
      category: "Creative catalog",
      source: "Company upload",
      status: "Indexed",
      access: ["Emmy", "Cine", "Jack", "Nova"],
      notes: "Released and unreleased song inventory with campaign status.",
      updatedAt: now,
    },
    {
      id: "knowledge-accounting-policy",
      title: "Company Bookkeeping Rules",
      workspaceId: "workspace-triple-hay",
      category: "Finance policy",
      source: "Michael P Records",
      status: "Draft",
      access: ["Michael P", "Adedeji", "Ayobami"],
      notes: "Approval rules, categories, retention periods, and monthly close checklist.",
      updatedAt: now,
    },
  ],
  memories: [
    {
      id: "memory-zip-workflow",
      title: "RoyalOS heavy upgrade workflow",
      workspaceId: "workspace-choice-royals",
      kind: "Development preference",
      source: "CEO conversation",
      content: "Use the latest backed-up working ZIP as the source of truth, then copy .env.local privately after extraction.",
      pinned: true,
      createdAt: now,
    },
    {
      id: "memory-content-engine",
      title: "Content is central to the journey",
      workspaceId: "workspace-triple-hay",
      kind: "Strategic decision",
      source: "CEO conversation",
      content: "RoyalOS must connect content creation, media production, social publishing, analytics, and company records.",
      pinned: true,
      createdAt: now,
    },
    {
      id: "memory-ifeoluwa-history",
      title: "Preserve Ifeoluwa conversations",
      workspaceId: "workspace-choice-royals",
      kind: "Product requirement",
      source: "CEO instruction",
      content: "New chat must start a separate conversation while previous chats remain available to reopen and continue.",
      pinned: false,
      createdAt: now,
    },
  ],
  messages: [
    {
      id: "message-cine-plan",
      from: "Cine",
      to: "Ayobami",
      subject: "Video production plan ready",
      body: "The Xena Grace vertical video plan is ready for provider connection and final approval.",
      workspaceId: "workspace-xena-grace",
      kind: "Employee",
      createdAt: now,
      read: false,
    },
    {
      id: "message-ledger-review",
      from: "Michael P",
      to: "Ayobami",
      subject: "One expense needs review",
      body: "A software transaction needs a final category before the monthly report can be completed.",
      workspaceId: "workspace-triple-hay",
      kind: "Employee",
      createdAt: now,
      read: false,
    },
    {
      id: "message-system-backup",
      from: "RoyalOS",
      to: "Ayobami",
      subject: "Backup workflow confirmed",
      body: "The current ZIP upgrade process has been recorded as the preferred heavy-update workflow.",
      workspaceId: "workspace-choice-royals",
      kind: "System",
      createdAt: now,
      read: true,
    },
  ],
  settings: {
    companyName: "Triple-Hay Concept LLC",
    founderName: "Ayobami",
    defaultWorkspaceId: "workspace-choice-royals",
    approvalRequired: true,
    socialPublishingApproval: true,
    accountingApproval: true,
    apiMonthlyBudget: 150,
    notificationsEnabled: true,
    autoBackupEnabled: true,
    dataRegion: "United States",
  },
};
